export const BSOUNDS = [
    "bsounds/scary_tiktok_music.mp3",
    "bsounds/sound5.mp3",
    "bsounds/streetfood_franklin_ringtone.mp3",
    "bsounds/sound4.mp3",
    "bsounds/air.mp3",
    "bsounds/industrial_society_and_its_future.mp3",
    "bsounds/classical_ah_sound.mp3",
    "bsounds/samsung_royal_ringtone.mp3",
    "bsounds/I pledge allegiance to the flag.mp3",
    "bsounds/sound2.mp3",
    "bsounds/canned_chicken.mp3",
    "bsounds/ignore_my_yawn_extended.mp3",
    "bsounds/gah_dayum_extended.mp3",
    "bsounds/fortnite_og_lobby_music.mp3",
    "bsounds/cough.mp3",
    "bsounds/csgo_menu_music.mp3",
    "bsounds/its_been_a_fing_year.mp3",
    "bsounds/sound6.mp3",
    "bsounds/degrease_me.mp3",
    "bsounds/break_from_the_ads.mp3",
    "bsounds/sound3.mp3",
    "bsounds/sound1.mp3",
    "bsounds/mmm_ringtone.mp3",
    "bsounds/flight_announcement.mp3",
    "bsounds/wet_bubby_sounds.mp3"
];
